# Triggers on tags v*; creates/updates GitHub Release using git-cliff output.
name: Create GitHub Release from CHANGELOG

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

# Requires default GITHUB_TOKEN with 'contents: write' to call gh release.
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    # One run per ref; avoids duplicate releases on rapid retags.
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: false
    steps:
      # fetch-depth 0 is required so git-cliff sees tags/history.
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      # Validates v*-style semver tag and exposes 'version' for later steps.
      - name: Derive version from tag
        id: version
        shell: bash
        run: |
          ref="${GITHUB_REF_NAME}"
          version="${ref#v}"
          if [[ -z "$version" || "$ref" == "$version" ]]; then
            echo "Error: Expected tag to start with 'v', got '$ref'"
            exit 1
          fi
          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-].*)?$ ]]; then
            echo "Error: Tag '$ref' is not semver-like (vMAJOR.MINOR.PATCH[-prerelease])"
            exit 1
          fi
          echo "version=$version" >> "$GITHUB_OUTPUT"

      # Uses git-cliff to render the section for this tag; keep formatting consistent with CHANGELOG.md.
      - name: Generate changelog content for this tag
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          # If you have a configuration file, set it here:
          # config: cliff.toml
          args: --tag "v${{ steps.version.outputs.version }}" --context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Treats versions containing '-' as prerelease (e.g., 1.2.3-beta.1).
      - name: Determine prerelease
        id: prerelease
        shell: bash
        run: |
          v="${{ steps.version.outputs.version }}"
          if [[ "$v" == *-* ]]; then
            echo "is_prerelease=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_prerelease=false" >> "$GITHUB_OUTPUT"
          fi

      # Uses gh to create/edit release; notes-file avoids shell escaping issues; RELEASE_COMMIT=github.sha.
      - name: Create or update GitHub Release using CHANGELOG
        env:
          RELEASE_COMMIT: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
          CHANGELOG: ${{ steps.git-cliff.outputs.content }}
          IS_PRERELEASE: ${{ steps.prerelease.outputs.is_prerelease }}
        shell: bash
        run: |
          notes="${CHANGELOG:-No changelog entry found for version ${VERSION}}"
          printf '%s' "$notes" > RELEASE_NOTES.md

          if gh release view "v$VERSION" >/dev/null 2>&1; then
            echo "Release v$VERSION already exists. Updating..."
            gh release edit "v$VERSION" \
              --target "$RELEASE_COMMIT" \
              --title "Release $VERSION" \
              --prerelease="$IS_PRERELEASE" \
              --notes-file RELEASE_NOTES.md
          else
            echo "Creating release v$VERSION..."
            gh release create "v$VERSION" \
              --target "$RELEASE_COMMIT" \
              --title "Release $VERSION" \
              --prerelease="$IS_PRERELEASE" \
              --notes-file RELEASE_NOTES.md
          fi
