name: Release & Publish Node.js Package

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish:
    # Only run if both conditions are met:
    # 1. It's a tag push (which we ensure from the 'on' trigger)
    # 2. The commit message starts with 'release/'
    if: |
      github.ref == 'refs/heads/main' &&
      startsWith(github.event.head_commit.message, 'release:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      # Get version from package.json
      - name: Get version
        id: package-version
        run: |
          echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      # Create and push tag if it doesn't exist
      - name: Create and push tag
        id: create-tag
        run: |
          VERSION=${{ steps.package-version.outputs.version }}
          TAG="v${VERSION}"

          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
            git tag -a "$TAG" -m "Release version $VERSION"
            git push origin "$TAG"
            echo "created=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG already exists"
            echo "created=false" >> $GITHUB_OUTPUT
          fi

      # Update CHANGELOG.md with latest changes
      - name: Update CHANGELOG
        run: |
          VERSION=${{ steps.package-version.outputs.version }}
          make changelog $VERSION
          # Stage the updated CHANGELOG
          git add CHANGELOG.md
          git commit -m "docs: update changelog for version $VERSION"

      # Check if this is a prerelease by inspecting the commit message
      - name: Check prerelease status
        id: prerelease
        run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          if [[ "$MESSAGE" =~ ^release/.*prerelease ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      # Validate that the package version matches the tag version
      - name: Validate version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PACKAGE_VERSION=${{ steps.package-version.outputs.version }}
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build (if needed)
        run: npm run build --if-present

      - name: Run tests
        run: npm test --if-present

      # Check if this version already exists on the registry
      - name: Check if version exists
        id: version-exists
        run: |
          VERSION=${{ steps.package-version.outputs.version }}
          # Replace 'your-package-name' with the actual name from your package.json if needed.
          if npm view your-package-name versions | grep -q "\"$VERSION\""; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # Create GitHub Release using the CHANGELOG file
      - name: Create Release using CHANGELOG
        env:
          RELEASE_COMMIT: "${{ github.sha }}"
        run: |
          VERSION=${{ steps.package-version.outputs.version }}
          # Extract the changelog section for the version.
          # This awk command assumes that your CHANGELOG follows a format
          # where each version section starts with a header like "## [1.0.0]"
          # and sections are separated by headers.
          NOTES=$(awk -v ver="## [${VERSION}]" '
            BEGIN { capture=0 }
            $0 ~ ver { capture=1; next }
            /^## \[/ { if(capture==1) { capture=0 } }
            capture { print }
          ' CHANGELOG)

          # If no notes are found, optionally warn and use the whole CHANGELOG.
          if [ -z "$NOTES" ]; then
            echo "No changelog section found for version $VERSION. Using full CHANGELOG."
            NOTES=$(cat CHANGELOG)
          fi

          # Write the extracted notes to a temporary file to safeguard against quoting issues.
          echo "$NOTES" > $RUNNER_TEMP/notes.txt

          # Use GitHub CLI to create the release.
          # Adjust the gh command as needed; here we use the tag (without the leading 'v') as the release tag.
          gh release create "${GITHUB_REF#refs/tags/}" \
            --target "$RELEASE_COMMIT" \
            --title "Release $VERSION" \
            --notes-file "$RUNNER_TEMP/notes.txt"

      # Publish package if the version is not already published
      - name: Publish package
        if: steps.version-exists.outputs.exists != 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Rollback on failure
      - name: Rollback on failure
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=${{ steps.package-version.outputs.version }}
          TAG="v${VERSION}"
          echo "Rolling back release version $VERSION..."

          # Delete the tag locally and remotely if we created it
          if [[ "${{ steps.create-tag.outputs.created }}" == "true" ]]; then
            git tag -d "$TAG" || true
            git push --delete origin "$TAG" || true
          fi

          # Revert the changelog commit if it exists
          if git log -1 --pretty=%B | grep -q "docs: update changelog for version $VERSION"; then
            git revert HEAD -n
            git commit -m "revert: rollback changes for version $VERSION"
            git push origin main
          fi

          # Execute rollback using make command
          echo "Y" | make release-rollback $VERSION

          echo "Release $VERSION has been rolled back."

      # Enhanced failure notification
      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Failed to publish package or create release. A rollback has been attempted. Check the logs for more details."
